/// Centralized product language for the local MVP experience.
///
/// [productName] is intentionally the single source of truth for the temporary
/// working name so it can be replaced without searching through feature code.
abstract final class AppCopy {
  static const String productName = 'Aira';
  static const String aiCompanionLabel = 'AI companion';
  static const String fictionalAiLabel = 'Fictional AI';
  static const String appTitle = '$productName - $aiCompanionLabel';

  // Onboarding and identity.
  static const String onboardingEyebrow = 'A CLEARLY IDENTIFIED AI EXPERIENCE';
  static const String onboardingTitle = 'Meet $productName';
  static const String onboardingBody =
      'Every companion in $productName is a fictional AI character. Their '
      'portraits do not represent real people, and their responses are '
      'generated by artificial intelligence and may sometimes be inaccurate.';
  static const String ageRequirementTitle = 'For adults 18 and over';
  static const String ageRequirementBody =
      'You must be at least 18 years old to use this experience.';
  static const String ageConfirmationLabel =
      'I confirm that I am 18 years old or older';
  static const String continueLabel = 'Continue';
  static const String supportBoundary =
      '$productName offers general conversation, not medical care or emergency '
      'support. If you may be in danger, contact local emergency services.';

  // Home.
  static const String homeGreeting = 'A calm space to check in';
  static const String homeSupportingText =
      'Take a moment for a short conversation with your AI companion.';
  static const String nextConversationTitle = 'Next scheduled conversation';
  static const String noConversationScheduled = 'Nothing scheduled yet';
  static const String startConversationLabel = 'Start conversation';
  static const String localMockLabel = 'Local mock experience';

  // Mock voice call.
  static const String voiceConversationTitle = 'Voice conversation';
  static const String listeningState = 'Listening';
  static const String speakingState = 'Speaking';
  static const String callDurationLabel = 'Call duration';
  static const String muteLabel = 'Mute';
  static const String unmuteLabel = 'Unmute';
  static const String endCallLabel = 'End call';
  static const String mockCallNotice =
      'Local mock only. No audio is recorded, played, or sent.';

  // Schedule.
  static const String scheduleTitle = 'Schedule';
  static const String scheduleHeading = 'Plan a conversation';
  static const String scheduleSupportingText =
      'Choose when you would like a reminder to start an AI conversation.';
  static const String preferredTimeLabel = 'Preferred time';
  static const String repeatOnLabel = 'Repeat on';
  static const String saveScheduleLabel = 'Save schedule';
  static const String scheduleSavedMessage = 'Schedule saved on this device';

  // Settings, memory, and privacy.
  static const String settingsTitle = 'Settings';
  static const String memorySectionTitle = 'Memory';
  static const String memoryOptInTitle = 'Allow long-term memory';
  static const String memoryOptInDescription =
      'Choose whether $productName may remember selected details in a future '
      'version. This prototype does not provide persistent conversation memory.';
  static const String viewMemoryLabel = 'View memory';
  static const String viewMemoryPlaceholder =
      'No memories are stored in this local mock.';
  static const String deleteMemoryLabel = 'Delete all memory';
  static const String deleteMemoryPlaceholder =
      'There is no saved memory to delete.';
  static const String privacySectionTitle = 'Privacy';
  static const String privacySummary =
      'Aanya voice turns send temporary microphone audio only to your trusted '
      'local Aira service. No cloud account or long-term memory is used.';
  static const String aiDisclosureTitle = 'About this AI';
  static const String aiDisclosureBody =
      '$productName is artificial intelligence, not a person. It cannot '
      'provide professional care or emergency response.';

  // Navigation.
  static const String homeNavigationLabel = 'Home';
  static const String scheduleNavigationLabel = 'Schedule';
  static const String settingsNavigationLabel = 'Settings';
}
